### ISSUE TITLE
xlxs写入文件跨行跨列处理

### ISSUE THREAD

**Issue by baocaixiong** [bronze1man/kmg#6]
很抱歉我是从[/tealeg/xlsx](https://github.com/tealeg/xlsx) 看见您的issue过来。
英文太渣，不好问老外。
麻烦提示一下使用[tealeg/xlsx](https://github.com/tealeg/xlsx)模块如何处理xlxs文件的跨行跨列问题。

另外有个概念性的问题。在[tealeg/xlsx](https://github.com/tealeg/xlsx/blob/master/sharedstrings.go)以及[encoding/kmgExcel/XlsxWriter.go](https://github.com/bronze1man/kmg/blob/master/encoding/kmgExcel/XlsxWriter.go#L36)中都有提到 `SharedStrings`的概念，应该如何理解？ 

谢谢啦~~

**Comment by bronze1man** [comment]
这个issues时间太旧了,关闭
